---

name: Test Galaxy Tool XML

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  planemo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install Python dependencies (uv will install python automatically, if no appropriate version is installed)
        run: uv sync --all-extras --dev
        shell: bash
      - name: Build Docker image
        run: docker buildx build -t daschswiss/fileidentification-galaxy:latest .
      - name: Run planemo e2e tests
        run: uv run planemo test --biocontainers --galaxy_root=.galaxy fileidentification-galaxy.xml
      - name: make test output available
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tool_test_output
          path: tool_test_output.*
          compression-level: 0
